### ISSUE TITLE
docker issue on recent hassos

### ISSUE THREAD

**Issue by gretel** [Rbillon59/hass-deepstack#2]
![image](https://user-images.githubusercontent.com/80815/231903426-b1f2a254-0ddc-470d-8fd6-ebb0d716054b.png)

```Dockerfile
RUN apt-get update
RUN apt-get -y install jq
```

think `update` is required cause `install` requires the package index to be present.

**Comment by Rbillon59** [comment]
Hello @gretel, I just tried to rebuild and reinstall the add-on on my personal instance and did not face any issue.

Could you please describe a bit more your installation and version?

Thank you

**Comment by gretel** [comment]
> Could you please describe a bit more your installation and version?

![image](https://user-images.githubusercontent.com/80815/231998923-52a2d7fd-2021-45d0-ad62-8eabb3e1d50a.png)

on rpi4. personally i'm using https://github.com/hadolint/hadolint to ensure valid `Dockerfile`.

**Comment by Rbillon59** [comment]
I just tried to update my instance and rebuild the add-on, it's working great. But I'm on amd64 arch.

I tried to build on arm and faced no issues.

I also ran hadolint against the Dockerfile (tool I did not know, thanks for the discovery) and no issues encountered.


Did you try multiple times ? The error shows an issue during the apt install phase. This could mean an issue downloading the package, so a possible networking issue. Also did you check the space left on your Rpi ? The base image is quite large and then tries to install the package. Could be a space issue as well.

**Comment by gretel** [comment]
@Rbillon59 thanks, and for checking with `hadolint`. we are both on the wrong track as the supervisor log indicates:

```
23-04-14 14:20:15 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 3cfc8f0f/aarch64-addon-hass-deepstack:0.0.1
23-04-14 14:21:38 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 3cfc8f0f/aarch64-addon-hass-deepstack:0.0.1: The command '/bin/sh -c apt install -y jq' returned a non-zero code: 1
23-04-14 14:21:38 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/9 : FROM deepquestai/deepstack:cpu
 ---> d39ec65c47f2
Step 2/9 : RUN apt install -y jq
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 887ac3a80e61
exec /bin/sh: exec format error
```

looks like the tagging is bit arbitrary 😄 https://hub.docker.com/layers/deepquestai/deepstack/arm64-server/images/sha256-5850e5046e1fd2f7a7f0c2676e607a1a4857e31016b232b727728b6220d29233?context=explore

**Comment by Rbillon59** [comment]
Oh true, so it's an issue with the CPU architecture.

I will check what I can do to support arm64

**Comment by gretel** [comment]
cool. think a "common solution" is to offer a repository per architecture 😞

**Comment by gretel** [comment]
btw, i'm also looking at https://github.com/grinco/HASS-coral-rest-api because i have a device but `frigate` without the paid models (`frigate+`) is not very usable in my case.

**Comment by Rbillon59** [comment]
I haven't a lot of time now, so I will probably touch that next week.

Also, I believe I will build multi arch Addon and publish directly the image to avoid having to built it locally

https://developers.home-assistant.io/docs/add-ons/publishing/#build-scripts-to-publish-add-ons-to-a-container-registry

**Comment by gretel** [comment]
sure thanks!

**Comment by Rbillon59** [comment]
Hi @gretel I've updated the addon so `aarch64`  should be buildable. Could you test to install the addon please ? I've no arm64 to test it

**Comment by gretel** [comment]
![Screenshot 2023-04-18 at 23 10 54](https://user-images.githubusercontent.com/80815/232906138-ac81506d-22b5-4148-bf35-25f49b262250.png)
![Screenshot 2023-04-18 at 23 10 48](https://user-images.githubusercontent.com/80815/232906147-5365d458-4b63-40a2-a741-1e989f8818e8.png)

thanks, looking quickly looks like it's werking fine!

**Comment by Rbillon59** [comment]
Awesome, I'am closing the issue, enjoy !
